# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/hoch/repos/SJSU-ANS_DeepRacer/ans_gui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1285, 564)
        MainWindow.setMinimumSize(QtCore.QSize(1285, 564))
        MainWindow.setMaximumSize(QtCore.QSize(1285, 564))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 521))
        self.centralwidget.setMaximumSize(QtCore.QSize(1285, 521))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_layout = QtWidgets.QHBoxLayout()
        self.title_layout.setObjectName("title_layout")
        self.title = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        self.title.setStyleSheet("font: 700 48pt \"Arial\";\n"
"color: rgb(25, 4, 143);\n"
"border: 2px solid rgb(25, 4, 143)")
        self.title.setObjectName("title")
        self.title_layout.addWidget(self.title, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addLayout(self.title_layout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.body_layout = QtWidgets.QHBoxLayout()
        self.body_layout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.body_layout.setObjectName("body_layout")
        self.status_controls_layout = QtWidgets.QVBoxLayout()
        self.status_controls_layout.setObjectName("status_controls_layout")
        self.status_layout = QtWidgets.QVBoxLayout()
        self.status_layout.setContentsMargins(-1, 0, -1, 0)
        self.status_layout.setSpacing(3)
        self.status_layout.setObjectName("status_layout")
        self.status_title = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status_title.sizePolicy().hasHeightForWidth())
        self.status_title.setSizePolicy(sizePolicy)
        self.status_title.setBaseSize(QtCore.QSize(0, 0))
        self.status_title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.status_title.setStyleSheet("font: 12pt \"Arial\";\n"
"text-decoration: underline;")
        self.status_title.setScaledContents(False)
        self.status_title.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.status_title.setObjectName("status_title")
        self.status_layout.addWidget(self.status_title, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.status_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status_label.sizePolicy().hasHeightForWidth())
        self.status_label.setSizePolicy(sizePolicy)
        self.status_label.setMinimumSize(QtCore.QSize(165, 80))
        self.status_label.setMaximumSize(QtCore.QSize(165, 80))
        self.status_label.setAlignment(QtCore.Qt.AlignCenter)
        self.status_label.setObjectName("status_label")
        self.status_layout.addWidget(self.status_label, 0, QtCore.Qt.AlignHCenter)
        self.status_layout.setStretch(0, 1)
        self.status_layout.setStretch(1, 5)
        self.status_controls_layout.addLayout(self.status_layout)
        self.controls_layout = QtWidgets.QVBoxLayout()
        self.controls_layout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.controls_layout.setObjectName("controls_layout")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.controls_layout.addWidget(self.line_3)
        self.command_title = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.command_title.sizePolicy().hasHeightForWidth())
        self.command_title.setSizePolicy(sizePolicy)
        self.command_title.setStyleSheet("font: 12pt \"Arial\";\n"
"text-decoration: underline;")
        self.command_title.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.command_title.setObjectName("command_title")
        self.controls_layout.addWidget(self.command_title, 0, QtCore.Qt.AlignTop)
        self.config_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.config_button.sizePolicy().hasHeightForWidth())
        self.config_button.setSizePolicy(sizePolicy)
        self.config_button.setMinimumSize(QtCore.QSize(165, 0))
        self.config_button.setMaximumSize(QtCore.QSize(165, 16777215))
        self.config_button.setBaseSize(QtCore.QSize(10, 0))
        self.config_button.setObjectName("config_button")
        self.controls_layout.addWidget(self.config_button, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.navigation_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.navigation_button.sizePolicy().hasHeightForWidth())
        self.navigation_button.setSizePolicy(sizePolicy)
        self.navigation_button.setMinimumSize(QtCore.QSize(165, 0))
        self.navigation_button.setMaximumSize(QtCore.QSize(165, 16777215))
        self.navigation_button.setObjectName("navigation_button")
        self.controls_layout.addWidget(self.navigation_button, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.data_collect_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_collect_button.sizePolicy().hasHeightForWidth())
        self.data_collect_button.setSizePolicy(sizePolicy)
        self.data_collect_button.setMinimumSize(QtCore.QSize(165, 0))
        self.data_collect_button.setMaximumSize(QtCore.QSize(165, 16777215))
        self.data_collect_button.setObjectName("data_collect_button")
        self.controls_layout.addWidget(self.data_collect_button, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.joystick_layout = QtWidgets.QHBoxLayout()
        self.joystick_layout.setObjectName("joystick_layout")
        self.joystick_widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.joystick_widget.sizePolicy().hasHeightForWidth())
        self.joystick_widget.setSizePolicy(sizePolicy)
        self.joystick_widget.setMinimumSize(QtCore.QSize(150, 0))
        self.joystick_widget.setMaximumSize(QtCore.QSize(150, 16777215))
        self.joystick_widget.setObjectName("joystick_widget")
        self.label_4 = QtWidgets.QLabel(self.joystick_widget)
        self.label_4.setGeometry(QtCore.QRect(-2, 0, 171, 20))
        self.label_4.setStyleSheet("font: 10pt \"Arial\";\n"
"text-decoration: underline;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.joystick_layout.addWidget(self.joystick_widget)
        self.speed_slider = QtWidgets.QSlider(self.centralwidget)
        self.speed_slider.setOrientation(QtCore.Qt.Vertical)
        self.speed_slider.setObjectName("speed_slider")
        self.joystick_layout.addWidget(self.speed_slider)
        self.joystick_layout.setStretch(1, 1)
        self.controls_layout.addLayout(self.joystick_layout)
        self.status_controls_layout.addLayout(self.controls_layout)
        self.status_controls_layout.setStretch(0, 1)
        self.status_controls_layout.setStretch(1, 3)
        self.body_layout.addLayout(self.status_controls_layout)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setObjectName("line_2")
        self.body_layout.addWidget(self.line_2)
        self.video_layout = QtWidgets.QVBoxLayout()
        self.video_layout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.video_layout.setContentsMargins(-1, 10, -1, -1)
        self.video_layout.setSpacing(0)
        self.video_layout.setObjectName("video_layout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(495, 0))
        self.label_2.setMaximumSize(QtCore.QSize(495, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.video_layout.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.image_label = QtWidgets.QLabel(self.centralwidget)
        self.image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label.setObjectName("image_label")
        self.video_layout.addWidget(self.image_label)
        self.video_layout.setStretch(0, 1)
        self.video_layout.setStretch(1, 10)
        self.body_layout.addLayout(self.video_layout)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.body_layout.addWidget(self.line_4)
        self.map_layout = QtWidgets.QVBoxLayout()
        self.map_layout.setContentsMargins(-1, 10, -1, -1)
        self.map_layout.setObjectName("map_layout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.map_layout.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.map_layout.addWidget(self.label)
        self.body_layout.addLayout(self.map_layout)
        self.body_layout.setStretch(0, 1)
        self.body_layout.setStretch(2, 3)
        self.body_layout.setStretch(4, 3)
        self.verticalLayout.addLayout(self.body_layout)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(2, 6)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1285, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "ANS DeepRacer Controller"))
        self.status_title.setText(_translate("MainWindow", "Status"))
        self.status_label.setText(_translate("MainWindow", "Initializing..."))
        self.command_title.setText(_translate("MainWindow", "Command"))
        self.config_button.setText(_translate("MainWindow", "Load configuration files"))
        self.navigation_button.setText(_translate("MainWindow", "Start navigation"))
        self.data_collect_button.setText(_translate("MainWindow", "Start data collect mode"))
        self.label_4.setText(_translate("MainWindow", "Drive Control"))
        self.label_2.setText(_translate("MainWindow", "DeepRacer Stereo Camera"))
        self.image_label.setText(_translate("MainWindow", "Video"))
        self.label_3.setText(_translate("MainWindow", "Mapped Environment"))
        self.label.setText(_translate("MainWindow", "Occupancy Map"))
